/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Memory_map.h>

int main(void)
{
		//1. Inicializacija - naredimo kazalec na ahb1en vodilo in omogocimo uro na portu G,A,F
		uint32_t* pAhb1enr = (uint32_t*)RCC_AHB1ENR;
		*pAhb1enr |= RCC_AHB1ENR_GPIOGEN;
		*pAhb1enr |= RCC_AHB1ENR_GPIOAEN;
		*pAhb1enr |= RCC_AHB1ENR_GPIOFEN;

		//2. Nastavimo pin PG13 na izhod
		uint32_t* gMODER = (uint32_t*)GPIOG_MODER;
		//postavimo PG13 na izhod, zelena led
		*gMODER |= 1 << 26;												//postavi 26 bit
		*gMODER &= ~(1 << 27);											//pocisti 27 bit

		//3. Vklop oziroma izklop LED diode, zelena, indikator če je tipka pritisnjena
		uint32_t* gODR = (uint32_t*)GPIOG_ODR;
		*gODR |= 1 << 13;

		uint32_t* fODR = (uint32_t*)GPIOF_ODR;

		//postavimo pin PA0 na vhod
		uint32_t* aMODER = (uint32_t*)GPIOA_MODER;
		*aMODER &= ~(3 << 0);

		//4. Inicializiramo izhodne pine za 7 segmentni display (PF0 - PF6) izhod je 01
		//Port F je omogočen že zgoraj

		uint32_t* fMODER =(uint32_t*)GPIOF_MODER;

		//PF0 postavimo na izhod
		*fMODER	|=	1<<0;
		*fMODER	&=	~(1<<1);

		//PF1 postavimo na izhod
		*fMODER	|=	1<<2;
		*fMODER	&=	~(1<<3);

		//PF2 postavimo na izhod
		*fMODER	|=	1<<4;
		*fMODER	&=	~(1<<5);

		//PF3 postavimo na izhod
		*fMODER	|=	1<<6;
		*fMODER	&=	~(1<<7);

		//PF4 postavimo na izhod
		*fMODER	|=	1<<8;
		*fMODER	&=	~(1<<9);

		//PF5 postavimo na izhod
		*fMODER	|=	1<<10;
		*fMODER	&=	~(1<<11);

		//PF7 postavimo na izhod
		*fMODER	|=	1<<12;
		*fMODER	&=	~(1<<13);

		uint32_t a=0;
		uint32_t prej=0;

		for(;;)
		{
			//preberi stanje gumba
			uint32_t* aIDR = (uint32_t*)GPIOA_IDR;

			//preberemo stanje registra in stanje bita
			uint32_t jeGumbPritisnjen = *aIDR & (1 << 0);

			//stanje gumba nastavimo kot stanje LED diode
			if(jeGumbPritisnjen != 0 && prej==0)
			{
				//preverimo, ce je gumb pritisnjen, zelena led sveti dokler je gumb pritisnjen
				*gODR |= 1 << 13;							//vklopi LED diodo
				if (a < 15)
				{
				a++;
				}
				else
				{
					a = 0;
				}
			}
			else
			{
				*gODR &= ~(1 << 13);						//izklopi LED diodo, če gumb ni pritisnjen
			}

			prej = jeGumbPritisnjen;
			zaporedje_LED(a);
		}
}
